module.exports = {
  up: async (queryInterface) => queryInterface.bulkInsert('items', [
    // ========================================= POPULAR CATEGORY
    {
      item_name: 'Kuki-Hojicha',
      description: 'Sourced from a family farm in Japan. This roasted green tea has notes of nuts, sesame, and a hint of caramel.',
      item_category: 'popular',
      price: 4.50,
      image_id: '001',
      available_in_temp: 'both',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      item_name: 'Kyoho Grape Oolong',
      description: 'This Kyoho Grape Oolong has a wonderful aroma of ripe juicy grapes balanced with the delicate flavors of high mountain Taiwanese oolong.',
      item_category: 'popular',
      price: 4.00,
      image_id: '002',
      available_in_temp: 'both',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      item_name: 'Golden Pomelo Oolong',
      description: 'A highly aromatic cup with the aroma of succulent golden pomelo. The infusion is smooth and velvety, with delectable citrus notes.',
      item_category: 'popular',
      price: 5.00,
      image_id: '003',
      available_in_temp: 'both',
      created_at: new Date(),
      updated_at: new Date(),
    },
    // ========================================= ESSENTIALS CATEGORY
    {
      item_name: 'Arakai Black',
      description: 'An Australian black tea sourced from a farm in Queensland. The tea infusion is medium bodied, with notes of spice, chocolate and malt.',
      item_category: 'essentials',
      price: 4.00,
      image_id: '004',
      available_in_temp: 'hot',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      item_name: 'Oriental Green',
      description: 'A smooth and delectable Taiwanese green tea with notes of nuts and seaweed. The infusion light and refreshing, with a mild sweetness.',
      item_category: 'essentials',
      price: 4.00,
      image_id: '005',
      available_in_temp: 'hot',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      item_name: 'High Mountain Pouchong Tea',
      description: 'A light oxidized tea that preserves its natural ingredients and antioxidants which are good for your health. ',
      item_category: 'essentials',
      price: 4.00,
      image_id: '006',
      available_in_temp: 'both',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      item_name: 'Dong Ding Oolong Tea',
      description: 'One of Taiwan’s most popular teas. Beautiful bright golden tea liquor, with complex notes of toasted nuts, ripe fruits and a hint of peach. Well-rounded with a medium roast.',
      item_category: 'essentials',
      price: 4.50,
      image_id: '007',
      available_in_temp: 'both',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      item_name: 'Vanilla Oolong',
      description: 'A pleasing cup laced with the alluring aroma of vanilla bean. This handcrafted oolong is fragrant and creamy, with a smooth velvety mouthfeel.',
      item_category: 'essentials',
      price: 4.00,
      image_id: '008',
      available_in_temp: 'both',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      item_name: 'Mint Oolong',
      description: 'A refreshing blend of mint and oolong, this tea is perfect for hot summer days. Also great as an iced tea or as a minty base for cocktails.',
      item_category: 'essentials',
      price: 4.00,
      image_id: '009',
      available_in_temp: 'both',
      created_at: new Date(),
      updated_at: new Date(),
    },
    // ========================================= BOTTLED CATEGORY
    {
      item_name: 'Kuki-Hojicha',
      description: 'Sourced from a family farm in Japan. This roasted green tea has notes of nuts, sesame, and a hint of caramel.',
      item_category: 'bottled',
      price: 6.00,
      image_id: '010',
      available_in_temp: 'both',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      item_name: 'Dong Ding Oolong Tea',
      description: 'One of Taiwan’s most popular teas. Beautiful bright golden tea liquor, with complex notes of toasted nuts, ripe fruits and a hint of peach. Well-rounded with a medium roast.',
      item_category: 'bottled',
      price: 6.00,
      image_id: '011',
      available_in_temp: 'both',
      created_at: new Date(),
      updated_at: new Date(),
    },
  ], {}),

  down: async (queryInterface) => {
    console.log('deleting seed data from items ==============>');
    await queryInterface.bulkDelete('items', null, {});
  },
};
